name: Go

on:
  push:
    branches:

      - master
  pull_request:
    branches:
      - master


jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1 
  test:
    name: Run unit tests
    runs-on:  windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.20
    - name: Run test
      run: go mod tidy && go test ./...

